server:
  port: 8080
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
        #      url: jdbc:mysql://127.0.0.1:6033/abscloud?useUnicode=true&characterEncoding=utf8
      url: jdbc:mysql://192.168.0.17:3306/abscloud?useUnicode=true&characterEncoding=utf8
      username: mysql
      password: mysql
        #username: sqhtech
        #password: j4#wYv&Q$^D#g9N3ukZoIAIHoOmK0E5r
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #stat是统计，wall是SQL防火墙，防SQL注入的，log4j是用来输出统计数据的
      filters: stat
        #Spring监控，对内部各接口调用的监控
        aop-patterns: com.songshushan.servie.*
        #对url进行统计
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/actuator/*'
        #访问界面
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #禁止手动重置监控数据
          reset-enable: false
          login-username: druid
          login-password: druid123
        filter:
          stat:
            log-slow-sql: true

